### ISSUE TITLE
Add HTML endpoints for profiles

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-rest#18]
- mustache templates to render profiles
- navigation between rules

**Comment by rstorey** [comment]
I'm not sure what the intention behind the desire to create mustache templates to render the profiles might be, but one could also link to these pages - which are already inter-linked.

PDF/A https://www.loc.gov/preservation/digital/formats/fdd/fdd000318.shtml
PDF/A-1 https://www.loc.gov/preservation/digital/formats/fdd/fdd000125.shtml
PDF/A-2 https://www.loc.gov/preservation/digital/formats/fdd/fdd000319.shtml
PDF/A-3 https://www.loc.gov/preservation/digital/formats/fdd/fdd000360.shtml

I added a bit more information to my link labels to help unfamiliar users immediately understand the differences among the profiles:
PDF/A-1 - ISO 19005-1 - Uses PDF 1.4
PDF/A-2 - ISO 32000-1 - Uses PDF 1.7
PDF/A-3 - ISO 32000-1 - Uses PDF 1.7 with embedded files

I can submit a pull request if this is something like what you want.

**Comment by bdoubrov** [comment]
Closing this issue as fixed / outdated
