### ISSUE TITLE
Add the ability to pass the reference to the file to be processed by the service via file path instead of sending the file over the network

### ISSUE THREAD

**Issue by jmaferreira** [veraPDF/veraPDF-rest#21]
Siegfried and Clamv Anti virus have a service/daemon operational mode. You may look at this for inspiration. 

Being able to operate the suggested way decreases dramatically the time necessary to process a large number of files as it reduces the need to boot up the java virtual machine for each file and to pass large chunks of data over the network.

**Comment by luis100** [comment]
- [ ] REST POST method
- [ ] REST GET method that receives file/directory path
- [ ] Method to easily set up the REST server
- [ ] Instructions on how to set up a UNIX service

## REST POST method
Have REST methods to receive the file to be processed via POST. Attach a file as form-data with the key "file".

```
POST /verapdf(?format=xml|json)
```
E.g. `curl localhost:9876/verapdf -F file=@myfile.pdf`

## REST GET method that receives file/directory path
Have to receive the file path via get (inspired by Siegfried which does not read the whole file). Have the file path encoded with base64 to deal with special characters and encodings. Allow to resursively transverse a directory finding all files/pdfs (possibly filter out files by name, see [linux find](http://man7.org/linux/man-pages/man1/find.1.html)). 

```
GET /verapdf/base64_encoded_file_name_or_directory(?nr=true&format=xml|json)
```
E.g. `http://localhost:9876/verapdf/YzpcTXkgRG9jdW1lbnRzXGhlbGxvX3dvcmxkLmRvYw==`

## Method to easily set up the REST server

For example, `verapdf -serve localhost:9876`

The REST server should be able to recover from service faults, including out of memory errors and infinitely hanging processes (e.g. with a timeout).

## Instructions on how to set up a UNIX service

Add instructions, and possibly include samples and install scripts, to easily install UNIX service to automatically start the verapdf REST service on startup (e.g. [supervisord](http://supervisord.org)).

**Comment by rstorey** [comment]
You might want to check out the pull request for the Docker method of building and running. In this way it can be run as a daemon within a container. I also submitted a (separate) pull request that accepts a file by PUT and autodetects the validation profile information. My fork has a branch with all my pull requests integrated. I am working now on validating a file (or directory of files) on the local disk by sending a filepath rather than by uploading the file over http(s).

**Comment by rstorey** [comment]
I have a branch here with a GET method that processes a directory of files:
https://github.com/rstorey/veraPDF-rest/tree/feature/process_files
This branch is also merged into my integration branch. I am working now on recursing through subdirectories to get all PDF files.
