### ISSUE TITLE
Page refresh is needed to re-use the form

### ISSUE THREAD

**Issue by rstorey** [veraPDF/veraPDF-rest#34]
Steps to reproduce:
1. Select a file in step 1, click Next.
2. Select a profile in step 2, click Next.
3. Click the circle for step 2, change the selected profile, click Next. Then click circle 3.
4. Click the circle for step 1, change the selected file, click Next.

Observed behavior:
1. When I try to go back to step 2 to change my selection and repeat the previous operation, nothing happens when I click next. When I click circle 3, an Exception message appears briefly and then I get the same report as I did the first time I was on step 3.
2. If change the selected file and attempt to repeat the same operation (without refreshing the page) I get the same validation report as I did the first time.

Expected behavior:
1. It should be more clear to end users that a page refresh is required to perform a new operation.
2. It's not obvious that the form inputs, which aren't disabled and can have their inputs changed, have no effect on the resulting report on step 3 unless/ until the page is refreshed.

Notes:
It seems like maybe some instructions are needed and/or perhaps the form inputs should be disabled once the form is used. I don't want to disappear the report without some kind of intentional user action because they might not have saved the report results from the previous operation. I'm working on this in my fork, but I'm not sure what the best solution might be yet.

**Comment by carlwilson** [comment]
Hi @rstorey, alas this isn't solved yet, but there's something rotten in Denmark regarding re-initialisation and it will be in the JavaScript.....
