### ISSUE TITLE
Add version number to the footer

### ISSUE THREAD

**Issue by Snipx** [veraPDF/veraPDF-rest#38]
As a user of veraPDF, I would prefer knowing exactly which version of the validation library the demo at http://demo.verapdf.org/ is based upon.

It doesn't matter where exactly this information is placed, but I think the footer is the most natural place.

**Comment by rstorey** [comment]
This might be a good place for it: http://demo.verapdf.org/api/info - with a link to this page from the footer.

**Comment by rstorey** [comment]
I have a branch here with a start towards this approach: https://github.com/rstorey/veraPDF-rest/tree/feature/api_info

**Comment by carlwilson** [comment]
First cut in #44
