### ISSUE TITLE
have a generated openAPI/swagger specification

### ISSUE THREAD

**Issue by jstaerk** [veraPDF/veraPDF-rest#52]
openAPI is a file format which specifies machine-readably how REST APIs can be used, with the swagger editor one can then create sample clients in 53 languages. There is a swagger/openapi plugin for dropwizard which allows that the according swagger.yml file is created automatically from some annotations.  

Somebody who presents this (unfortunately in german) https://media.ccc.de/v/froscon2017-1985-einfache_rest-apis_mit_dropwizard_und_swagger (Slides https://programm.froscon.de/2017/system/event_attachments/attachments/000/000/469/original/20170818_LeanIX_Presentation_Froscon.pdf )

VeraPDF-Rest brought me to dropwizard. I'm using the swagger plugin on my own project ( https://github.com/ZUGFeRD/mustangserver ) and I would like to try to integrate it with verapdf-rest. First step: upgrade dropwizard to exactly that version which works with the swagger plugin.
Second step: add some annotations, maybe use a bundle, change the config file slightly.

**Comment by marti1125** [comment]
Hi I have experience with swagger + java. I could help you!

**Comment by carlwilson** [comment]
Hi @jstaerk, and welcome @marti1125, good to make your virtual acquaintance, I've assigned you both to this issue for now. The pause for thought might present an opportunity to clean this up slightly. I recently based a [JHOVE REST demonstrator](https://github.com/openpreserve/jhove-rest/) on the veraPDF one. I did make some improvements, one of which was to separate the Dropwizard server parts from the REST resources, which are two separate modules: https://github.com/openpreserve/jhove-rest/. My main aim was to ensure that the [REST resource project only depended on the standard JAX-RS annotations](https://github.com/openpreserve/jhove-rest/blob/master/jhove-rest-resources/pom.xml#L13). I'd expect swagger tools based on JAX-RS might be a little easier to come by. It does mean extending the scope of the issue some; it's up to you?

**Comment by jstaerk** [comment]
Since there is a PR for this issue (#53) maybe JHOVE REST would deserve it's own ticket. I might be able to help there but to be honest it's the first time I hear of jax-rs.
PS: Please note that swagger automatically embeds it's HTML5 client, i.e. you get a web gui where you can try the methods (incl. uploading files) on http://127.0.0.1:6000/swagger

**Comment by carlwilson** [comment]
@jstaerk I'm happy to create a ticket (or you could if you fancy). I have updated the build dependencies there so it will now work. I'll get to this PR before the call tomorrow :), many thanks
